build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/ClinicalSummary.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/MetaLike.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala

When Clinical Summary is pushed by Redox, it has event types of either PatientPush or VisitPush. These types has not been supported
Part of https://github.com/vital-software/api/issues/207

support clinical summary updates that arrive by push from Redox

---

build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala

Colliding dependencies:
- scala-redox depends on "com.typesafe.play" %% "play-ahc-ws-standalone" % "1.0.0-RC1"
- api depends on "com.typesafe.play" %% "play-ws" % "2.5.2"
Unfortunately, play-ws jar does not depend on play-ws-standalone, but has the class inside itself. So it is not possible to exclude transitive dependency from the sbt. Instead, I replaced play-ahc-ws-standalone with play-ws in scala-redox project. It fixes the problem now, but it will be hard to keep dependencies in sync in both projects.

Fix collision of dependencies

---

src/main/scala/com/github/vitalsoftware/scalaredox/models/ClinicalSummary.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala

see https://developer.redoxengine.com/ClinicalSummary.html, under VisitQueryResponse
@apatzer, was there a reason we have only one case class for two types of Clinical Summary?
Also, there seems to be a bug with the return type of VisitNumber. Documentations says it is string, but the endpoint return integer. I will talk to the support soon. For now, I just commented the field out.

add case class VisitQueryResponse

---

build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Insurance.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/util/JsonOps.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/PatientSearchTest.scala

Otherwise, DateTime will pull in the local timezone of the server during
Json deserialization, which is not desired.

Use LocalDate instead of DateTime when the format is "yyyy-MM-dd".

---

build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/client/Response.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Upload.scala
src/test/scala/com/github/vitalsoftware/scalaredox/RedoxTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/UploadTest.scala

Fix for #16 
* Had to remove 'play-ahc-ws-standalone' in place of 'play-ahc-ws' % 2.6.3, as the Multipart objects (mainly `FilePart`) is not available in the standalone package currently (reference: https://github.com/playframework/play-ws/issues/126).
* Followed directions from 'Sending Files Through Redox' page for requirements of client functionality (https://developer.redoxengine.com/data-exchange/sending-files-through-redox/).
* The `upload` method has a few default parameters to it, one for the `fileContentType` that will be used by the Source stream during materialization, and one for `contentLength`. The default content length is to allow for a 2MB file upload (bytes in decimal octets). This is set as a request header, which the backing http client will then pick up and submit the …

Adds Upload method for sending file to redox

---

.buildkite/Dockerfile
.buildkite/pipeline.yml
.dockerignore
README.md

* Build is still essentially `sbt test`
* Does the builds within a container (albeit one that isn't publicly available) for cleanliness

Move CI to Buildkite

---

.buildkite/pipeline.yml

So, we include `sbt` in the run command instead

Base image no longer has sbt as Docker entrypoint

---

build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/models/AdvanceDirective.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Immunization.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Problem.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Provider.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/SocialHistory.scala

Fixes #26
See [this file](https://github.com/playframework/playframework/blob/2.6.12/framework/project/Dependencies.scala) which defines the dependencies for play 2.6.12 (play-json versions are no longer in lock-step with the main framework's versions) for which versions we're upgrading to.

Upgrade play-json to 2.6.8, fix some types to agree with schema

---

CHANGELOG.md
build.sbt
project/plugins.sbt
version.sbt

- Adds a changelog
- Sets up sbt-release
- Doesn't actually perform releases automatically; releasing is a matter of running `sbt release`

Set up sbt-release to perform release versioning (manually)

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Insurance.scala
src/main/scala/com/github/vitalsoftware/util/JsonOps.scala
src/test/scala/com/github/vitalsoftware/scalaredox/RedoxTest.scala

- `Insurance.Plan` changed from `InsurancePlan` to `Option[InsurancePlan]`
- That's because the plan may be a "null subtree" (all properties null), in which case it is not guaranteed to be set
- Null subtree algorithm now removes nulls from arrays
- Previously, if null-subtree objects were wrapped in an array, the subtree removal would replace the objects with JsNull values, but leave them in the array (causing a later error), e.g.
```json
"Orders": [
{
"Diagnoses": [
{
"Code": null,
"Codeset": null,
"Name": null,
"Type": null
}
]
}
]
```
previously became
```json
"Orders": [
{
"Diagnoses": [null]
}
]
```
but will now become
```json
"Orders": [
{
"Diagnoses": []
}
]
```

Make the null-subtree algorithm remove nulls from arrays

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/GroupedOrdersTest.scala

Two separate issues fixed in this PR:
- The `RedoxClient` wasn't considering the event type of order events, such that it would never parse a GroupedOrdersMessage
- `Patient.Demographics.Sex` was a required field, but we've seen events where it is `null`
- Read `Meta.EventType` and use it (in combination with the existing `Meta.DataModel`) to decide how to parse a Redox message
- Treat `null` values in `Patient.Demographics.Sex` the same as a value of `Unknown`

Fixes for grouped order parsing and optional Patient.Demographics.Sex field

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Document.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/HasVisitInfo.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala

Adds a simple `HasVisitInfo` trait that marks models with a `Visit: Option[VisitInfo]` property

Add a HasVisitInfo trait

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/util/JsonOps.scala
src/test/scala/com/github/vitalsoftware/util/JsonOpsTest.scala

We've been seeing testing messages from Redox that have quite sparse values. Sometimes we see even quite reliable fields come through as `null` (e.g. LastName), so we need to be quite good at pruning these subtrees.
The existing pruning approach didn't cope well with empty arrays as properties of an object.
- Adds a new JsValue method: `reduceEmptySubtrees`
- Adds a new `JsonOpsTest` to test both the empty and null reducers
- Adds a new optional constructor parameter to the `RedoxClient` allowing the `reducer: JsValue => JsValue`) to be specified
- Default value is `reduceNullSubtrees`, so this PR is completely BC (and new parameter is at end of list for anyone who was specifying the implicit parameters already)
So, to use the new pruning, you'd:
```scala
val client = new …
```

Allow better pruning of subtrees that are empty

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala

In a previous PR, we added a reducer argument to the RedoxClient constructor, allowing the user of the client to prune or otherwise alter a JsValue to their taste.

Add a reducer argument to RedoxClient.webhook()

---

build.sbt
project/plugins.sbt

Relates to #33
Configuration taken from https://github.com/xerial/sbt-sonatype#using-with-sbt-release-plugin - previously, we were relying on publishArtifacts which does "auto-staging", and wouldn't get promoted (because things weren't signed with PGP)
Also, with the new version of sbt-sonatype we can set credentials using env vars.

Perform Sonatype release correctly

---

.buildkite/pipeline.yml
CHANGELOG.md
build.sbt
version.sbt

Fixes #33
- Normal master builds don't cause a release
- Adds a "block step", which allows a developer to click the "release" button to cause an automated release from that build
- Reduces the number of cross-build versions we use (many were the same binary version anyway)
- Bumps the major version to 1

Perform automated releases in CI

---

src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/GroupedOrdersTest.scala

Also removes duplicate types "M" and "F" which are no longer supported by Redox.

Per vital-software/api#938, rename "gender" to "sex".

---

build.sbt
project/build.properties
project/plugins.sbt
version.sbt

- Upgrade SBT to 1.1.6
- One plugin upgraded
- Fix for breaking changes (in SBT 1.0) to use `/` for specifying coordinates, instead of `in`

Upgrade to SBT 1.1

---

build.sbt
project/build.properties
project/plugins.sbt
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ConnectionTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/FlowSheetTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/GroupedOrdersTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/MediaTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/NotesTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/OrderTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/PatientSearchTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ResultsTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/UploadTest.scala
version.sbt

Builds on #48 
Fixes #47 
Upgrades specs2 to 4.2.0, which has a version available for Scala 2.12, fixing our cross-build release process
Probably the only interesting thing is that we no longer need the `NoTimeConversions` trait

Upgrade specs2 to the latest version

---

CHANGELOG.md
build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/models/AdvanceDirective.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Allergy.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Document.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Encounter.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/MedicalEquipment.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Medication.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/PlanOfCare.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Problem.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Procedures.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Provider.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/SocialHistory.scala
version.sbt

- Upgrade `json-annotations` version that does robust json parsing and fallback to defaults when parsing fails.
- Assign defaults to data models without changing type signature.

Fallback to defaults

---

CHANGELOG.md
build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/client/RedoxClientTest.scala
version.sbt

Connected to: vital-software/api#1135
Due to robust parsing, we can return a result while still having errors. We need to pass both potential result and the error back to the consumer. This changes the return type signature of `RedoxClient.Webhook` to return both error and result as a tuple of options. `(Option[JsError], Option[AnyRef])`

Recover from Json parsing errors

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/client/RedoxClientTest.scala

The non-macro version of robust parsing doesn't work recursively. Therefore we need to recover and prune deep json paths.

Prune deep json paths

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/AdvanceDirective.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Allergy.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/ClinicalSummary.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Document.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Encounter.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/FlowSheetMessage.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Immunization.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Insurance.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/MedicalEquipment.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Medication.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Meta.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/PlanOfCare.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Problem.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Procedures.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Provider.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/SocialHistory.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Upload.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VitalSigns.scala
src/main/scala/com/github/vitalsoftware/util/RobustPrimitives.scala
src/test/scala/com/github/vitalsoftware/util/RobustParsingTest.scala
src/test/scala/com/github/vitalsoftware/util/RobustPrimitivesTest.scala

Resolves #59 
Adds robust reads for scalar types. so that we can recover from parsing errors like having a JsString("123") in a place we're expecting an Int.
This further adds support for converting values like "true", "t", "1" to Booleans from JsStrings.

Robust primitive parsing

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/util/JsonOps.scala

We were getting values like "Unknown" for Language field from redox. However our database fields for language only support VARCHAR(3) and caused errors. This handles language field as `Option[java.util.Locale]` and defaults to None if we fail to parse it.

Handle language locale

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala

Resolves #68 
This adds a new enum value for ValueType called "FormattedText" and to handle multiple enum values for Order PriorityType, A mapping is added 
```
"ST" -> "Stat",
"RT" -> "Routine"
```

Fix order value type and priority enums

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
version.sbt

Connected to https://github.com/vital-software/api/issues/1364
PatientClass is important to identify the stage in the visit the patient is currently at. Since its a Required, Reliable field we can expect redox to send a set of values for this filed. Therefore better suited as an enum.
Redox documentation:
**Visit.PatientClass** `Reliable`, `Required`
Patient class is used in many EHRs to determine where to put the patient.
Examples: Inpatient, Outpatient, Emergency

Add PatientClass enum to visit info

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Meta.scala

Add `CancelledEvent` to Meta. This indicates the Type of event being canceled.
E.g. Arrival, Discharge, PreAdmit

Add cancelled event type to meta

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/util/JsonOps.scala
src/test/scala/com/github/vitalsoftware/scalaredox/models/CommonTest.scala
version.sbt

Connected to https://github.com/vital-software/api/issues/1336
https://github.com/vital-software/api/issues/1336 Is cased by our implicit `json.Formats[locale]` with validation getting masked form default `Locale` formats in play-json. To avoid this and to make the language type more specific, A `Language` type that wraps `java.util.Locale` is introduced.
This will ensure Language specific validations are done at the time we parse redox requests.

Fix Locale validation error

---

src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala

Making this a lazy val is enough but marked them @transient for good measure.
Another issue this might have caused is, accessing Enum values in constructor is not thread safe. Therefore a lazy value is recommended.

Make SexType serializable

---

src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Insurance.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Meta.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VitalSigns.scala

Connected to vital-software/api#1492
This makes jsonFormat implicits @transient to enable all Enumeration instances JavaSerializable.

Make jsonFormats implicits in Enumerations transient

---

CHANGELOG.md
build.sbt
version.sbt

Resolves #65 #67
Deprecates the cross build for 2.11 to enable sonatype release.

Fix sonatype release

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala

This fixes a compiler warning due to a non-exhaustive match

Fix non exhaustive match

---

.buildkite/pipeline.yml
.buildkite/report-compile-problems
.buildkite/run-tests-and-coverage
.buildkite/store-git-info
.codeclimate.yml
.dockerignore
.github/pull_request_template.md
Dockerfile
README.md
build.sbt
docker-compose.buildkite.yml
docker-compose.yml

Brings `scala-redox` tooling inline with our other projects, with the main addition being Test Coverage reporting.
Resolves #25
- Run CI commands in Docker container
- Output and upload test coverage reports from JUnit
- Add new badges to Readme file
- Add Github PR template
- Add Code Climate config for Scala
- Add Compile warning/error check to CI

Add test coverage support - resolves #25

---

CHANGELOG.md
build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/receiver/ReceiveController.scala
src/main/scala/com/github/vitalsoftware/scalaredox/receiver/RedoxRequest.scala
src/main/scala/com/github/vitalsoftware/util/JsonNaming.scala
src/test/scala/com/github/vitalsoftware/helpers/WithApplication.scala
src/test/scala/com/github/vitalsoftware/helpers/WithReceiveController.scala
src/test/scala/com/github/vitalsoftware/scalaredox/receiver/ReceiveControllerTest.scala
version.sbt

Adds ReceiveController, an abstract trait that can be used to implement a validated webhook-receiving endpoint for Redox messages.
Previously, this logic lived in individual projects that processed messages from Redox. Now, we'd like more than one other project to be able to validate Redox webhooks (in this particular case, for implementing R^SSO support), so we have cause to move this validation logic into scala-redox.

[API-23]: Add endpoint challenge/response and validation logic

---

CHANGELOG.md
build.sbt
src/main/scala/com/github/vitalsoftware/scalaredox/client/HttpClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClientComponents.scala
src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxTokenManager.scala
src/test/scala/com/github/vitalsoftware/helpers/WithReceiveController.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ConnectionTest.scala
src/test/scala/com/github/vitalsoftware/scalaredox/RedoxTest.scala
version.sbt

Adds the ability to handle multiple credentials for multiple sources.
Each source in redox has a unique set of api-key, api-secret credentials. If a client has multiple sources, this would have required creating multiple RedoxClients per each source.
However, redox-client constructed an internal WsClient (httpClient) and a akka schedule to manage the access-refresh Token lifecycle. This consumes unnecessary resources as each client would have created its own thread pool.
This PR:
- Abstracts away the token management to a seperate class `RedoxTokanManager` which handles storing and refreshing tokens.
- Redox client now only handle consuming of redox endpoints. The http client and token manager is injected in.
- HttpClient interface is added to unify play's internal `WSClient` and …

[API-87] Resolve: Manage multiple credentials for multiple sources

---

build.sbt
project/plugins.sbt

- Use sbt-update-lines instead of defining an `updateLine` function in build.sbt
- Use sbt-gpg instead of sbt-pgp
- sbt-pgp has no support for gpg2's truststore, meaning release signing is broken on OS X
- Updates the Scala and Play Framework 2.6.x versions

Update build plugins

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala
version.sbt

Related to [API-219]
Makes Demographics.dob optional as its not reliable in `PatientUpdate` messages.
[API-219]: https://vital-software.atlassian.net/browse/API-219

[API-219] make demographics dob optional

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Code.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/FlowSheetMessage.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Observation.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Procedures.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/VitalSigns.scala
version.sbt

- Renames `CodeSet` to `Codeset` to match Redox (so the value actually comes through from the JSON), and splits it into similar subtypes as `Code` (`..WithName` for things with a name as well as a Codeset, etc.)
- Splits `Observation` into four different subclasses, because the four places we currently use that class all have different properties (and, chiefly, the observations on a flowsheet have Codeset not CodeSystem)
Will change base of PR to master when #86 is merged.

Fix codeset versus codesystem modelling in observations

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Medication.scala
src/main/scala/com/github/vitalsoftware/scalaredox/models/Meta.scala

Related to [API-239]
MedicationsMessage had some incorrect properties:
- MedicationsMessage.Order.Indications are now a sequence instead of an Option
- MedicationsMessage.Visit now use VisitInfo instead of Visit
[API-239]: https://vital-software.atlassian.net/browse/API-239

[API-239] Fix medications message

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
src/test/scala/com/github/vitalsoftware/scalaredox/models/CommonTest.scala

Resolves [API-198]
Redox sometimes send Language value as "Other" for non-ISO standard values.
These "Other" values will get assigned the java.util.Locale.ROOT when deserialized.
> The root locale is the locale whose language, country, and variant are empty ("") strings.  This is regarded as the base locale of all locales, and is used as the language/country neutral locale for the locale sensitive operations.
[API-198]: https://vital-software.atlassian.net/browse/API-198

[API-198] Handle other locales

---

CHANGELOG.md
build.sbt
version.sbt

Upgrade to akka-http 10.1.8
10.0.14 was causing some incompatibility issues with some libraries when they tried to use this with play 2.7

Upgrade akka-http to 10.1.8

---

CHANGELOG.md
src/main/scala/com/github/vitalsoftware/scalaredox/models/Meta.scala

It's useful to be able to represent the Meta for a message that failed to be processed by the current version of scala-redox. This is already almost possible, because almost all the fields of `Meta` are optional.
The exceptions are the `DataModel` and `EventType` fields, which contain an `Enumeration`. A failed Redox message may contain an invalid (or new/unseen) value for one of those fields, which would prevent us instantiating a `Meta` for the message.
Essentially, this is the same as if we changed the `DataModel` and `EventType` fields on `Meta` into e.g. `Option[DataModel.Value]`. But without the BC break.

Add `Invalid` sentinel types to Meta's DataModel and EventType

---

version.sbt

The previous release failed to push the new version to master.
https://buildkite.com/vital/scala-redox/builds/250#9d855529-8fee-48b5-910e-7e5cf678ef73
The underlying issue of vital-bot access has been fixed. This just increases the version.

bump version to 8.0.3
